"use client";

import { useState } from "react";
import { ArrowUp, LoaderCircle, Sparkles } from "lucide-react";
import { formatMoney, getStatusTone } from "@/lib/format";
import type { AiAnswer } from "@/data/ai-service";

const prompts = ["哪些客户逾期未付款？", "哪些采购超过预算？", "哪些供应商欠票？", "未来 7 天要付多少钱？", "未来 30 天要收多少钱？", "公司未来 30 天有没有资金缺口？"];

export function AiAssistant() {
  const [question, setQuestion] = useState(""); const [asked, setAsked] = useState(""); const [answer, setAnswer] = useState<AiAnswer | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  async function ask(value = question) { if (!value.trim() || loading) return; setLoading(true); setError(""); setAsked(value); setQuestion(""); const response = await fetch("/api/ai", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ question: value }) }); const data = await response.json(); setLoading(false); if (!response.ok) { setError(data.error ?? "查询失败"); return; } setAnswer(data.answer); }
  return <div className="ai-layout"><aside className="ai-prompts"><div className="eyebrow">常用经营问题</div>{prompts.map((prompt) => <button className="ai-prompt" key={prompt} onClick={() => ask(prompt)}>{prompt}</button>)}</aside><section className="ai-chat"><div className="ai-messages">{!asked && !loading ? <div className="empty"><div><Sparkles /><strong>从一个经营问题开始</strong><div style={{ fontSize: 11, marginTop: 6 }}>回答只读，不会修改财务数据</div></div></div> : null}{asked ? <div className="message user">{asked}</div> : null}{loading ? <div className="message assistant"><div className="message-body"><LoaderCircle className="animate-spin" size={17} /> 正在查询底层业务数据...</div></div> : null}{error ? <div className="form-error">{error}</div> : null}{answer && !loading ? <div className="message assistant"><div className="message-title">{answer.title}</div><div className="message-body">{answer.conclusion}</div>{answer.totalCents !== undefined ? <div style={{ fontSize: 24, fontWeight: 720, margin: "12px 0" }}>{formatMoney(answer.totalCents, true)}</div> : null}{answer.items.length ? <div className="panel" style={{ margin: "12px 0" }}>{answer.items.map((item, index) => <div className="balance-row" style={{ padding: "11px 13px" }} key={index}><div><div className="balance-name">{item.name} {item.status ? <span className={`badge ${getStatusTone(item.status)}`} style={{ marginLeft: 6 }}>{item.status}</span> : null}</div><div className="balance-meta">{item.detail}</div></div><div className="balance-amount">{formatMoney(item.amountCents)}</div></div>)}</div> : null}<div className="message-body"><strong>数据依据：</strong>{answer.basis}<br /><strong>建议动作：</strong>{answer.action}</div></div> : null}</div><div className="ai-input-row"><input className="input" value={question} onChange={(event) => setQuestion(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") ask(); }} placeholder="询问应收、应付、超预算、欠票或资金缺口" /><button className="button primary" onClick={() => ask()} disabled={loading} aria-label="发送问题"><ArrowUp /></button></div></section></div>;
}
