"use client";

import Link from "next/link";
import { useState } from "react";
import { ArrowRight, Banknote, FileInput, FileOutput, HandCoins, ReceiptText, WalletCards } from "lucide-react";
import { ApprovalDetail } from "@/components/approval-detail";
import { formatDate, formatMoney, getStatusTone } from "@/lib/format";

type Item = Record<string, unknown> & { id: number; kind: string; priority: string };

function TodoTable({ title, items, onPayment }: { title: string; items: Item[]; onPayment?: (id: number) => void }) { return <section className="panel finance-todo"><div className="panel-header"><div><div className="panel-title">{title}</div><div className="panel-subtitle">{items.length} 项</div></div></div>{items.length ? <div className="finance-todo-list">{items.map((item) => <div className="finance-todo-row" key={`${item.kind}-${item.id}`}><div><span className={`badge ${getStatusTone(item.priority)}`}>{item.priority}</span><strong>{String(item.title)}</strong><div><Link href={`/projects/${item.projectId}`}>{String(item.projectName)}</Link> · {item.supplierId ? <Link href={`/suppliers/${item.supplierId}`}>{String(item.counterparty)}</Link> : String(item.counterparty)}</div></div><div className="finance-todo-amount"><strong>{formatMoney(Number(item.amountCents))}</strong><span>{formatDate(String(item.dueDate))}</span></div>{item.kind === "payment" && onPayment ? <button className="button small primary" onClick={() => onPayment(item.id)}>执行付款</button> : <Link className="icon-plain" href={item.kind.includes("invoice") ? "/invoices?new=1" : item.kind === "receivable" ? "/receipts?new=1" : "/payables"} aria-label="打开业务"><ArrowRight /></Link>}</div>)}</div> : <div className="finance-empty">当前无待办</div>}</section>; }

export function FinanceWorkspace({ data, role }: { data: { receivables: Item[]; payables: Item[]; payments: Item[]; supplierInvoices: Item[]; customerInvoices: Item[]; accounts: Record<string, unknown>[] }; role: string }) { const [paymentId, setPaymentId] = useState<number | null>(null); const [toast, setToast] = useState(""); return <><div className="quick-actions"><Link className="quick-action" href="/receipts?new=1"><HandCoins /><span>登记收款</span></Link><Link className="quick-action" href="/receivables"><ReceiptText /><span>查看应收</span></Link><Link className="quick-action" href="/payment-requests"><Banknote /><span>执行付款</span></Link><Link className="quick-action" href="/payables"><ReceiptText /><span>查看应付</span></Link><Link className="quick-action" href="/invoices?new=1"><FileInput /><span>登记进项票</span></Link><Link className="quick-action" href="/invoices?new=1"><FileOutput /><span>登记销项票</span></Link><Link className="quick-action" href="/accounts"><WalletCards /><span>查看账户</span></Link></div><div className="finance-work-grid"><TodoTable title="应收待办" items={data.receivables} /><TodoTable title="应付待办" items={data.payables} /><TodoTable title="已审批待付款" items={data.payments} onPayment={role === "finance" ? setPaymentId : undefined} /><TodoTable title="供应商欠票" items={data.supplierInvoices} /><TodoTable title="客户待开发票" items={data.customerInvoices} /><section className="panel"><div className="panel-header"><div><div className="panel-title">资金账户</div><div className="panel-subtitle">当前可用余额</div></div></div><div className="balance-list">{data.accounts.map((account) => <div className="balance-row" key={String(account.id)}><div><div className="balance-name">{String(account.name)}</div><div className="balance-meta">{String(account.companyName)} · {String(account.type)}</div></div><div className="balance-amount">{formatMoney(Number(account.balanceCents), true)}</div></div>)}</div></section></div>{paymentId ? <ApprovalDetail type="payment" id={paymentId} role={role} onClose={() => setPaymentId(null)} onDone={(message) => { setPaymentId(null); setToast(message); window.location.reload(); }} /> : null}{toast ? <div className="toast">{toast}</div> : null}</>; }
