"use client";

/* eslint-disable @next/next/no-img-element -- authenticated user uploads should bypass the image optimizer proxy */

import Link from "next/link";
import { useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { Check, ChevronRight, ImageOff, LoaderCircle, ShoppingCart, X } from "lucide-react";
import { formatMoney, getStatusTone } from "@/lib/format";

type Row = Record<string, unknown> & { id: number; projectId: number; companyId: number; supplierId?: number; status: string };
type Quote = Record<string, unknown> & { id: number; skuId: number; supplierId: number; status: string };

export function ProcurementWorkspace({ rows, quotes, canWrite, initialProjectId }: { rows: Row[]; quotes: Quote[]; canWrite: boolean; initialProjectId?: number }) {
  const router = useRouter(); const [projectId, setProjectId] = useState(initialProjectId ? String(initialProjectId) : "all"); const [category, setCategory] = useState("all"); const [room, setRoom] = useState("all"); const [status, setStatus] = useState("all"); const [supplier, setSupplier] = useState("all"); const [selected, setSelected] = useState<number[]>([]); const [detail, setDetail] = useState<Row | null>(null); const [requestOpen, setRequestOpen] = useState(false); const [error, setError] = useState(""); const [pending, startTransition] = useTransition();
  const values = (key: string) => Array.from(new Set(rows.map((row) => String(row[key] ?? "")).filter(Boolean))).sort();
  const filtered = useMemo(() => rows.filter((row) => (projectId === "all" || String(row.projectId) === projectId) && (category === "all" || row.category === category) && (room === "all" || row.room === room) && (status === "all" || row.status === status) && (supplier === "all" || String(row.supplierId ?? "") === supplier)), [rows, projectId, category, room, status, supplier]);
  const detailQuotes = detail ? quotes.filter((quote) => Number(quote.skuId) === detail.id) : [];
  function toggle(id: number) { setSelected((current) => current.includes(id) ? current.filter((value) => value !== id) : [...current, id]); }
  async function chooseQuote(quoteId: number) { if (!detail) return; setError(""); const response = await fetch("/api/procurement/select-quote", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ skuId: detail.id, quoteId }) }); const data = await response.json(); if (!response.ok) { setError(data.error ?? "选供失败"); return; } setDetail(null); startTransition(() => router.refresh()); }
  async function submitRequest(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); const form = new FormData(event.currentTarget); const response = await fetch("/api/procurement/request", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ skuIds: selected, paymentType: form.get("paymentType"), reason: form.get("reason") }) }); const data = await response.json(); if (!response.ok) { setError(data.error ?? "采购申请提交失败"); return; }
    const file = form.get("attachment"); if (file instanceof File && file.size) { const attachment = new FormData(); attachment.set("objectType", "purchase_request"); attachment.set("objectId", String(data.result.id)); attachment.set("category", "采购附件"); attachment.set("file", file); const upload = await fetch("/api/attachments", { method: "POST", body: attachment }); if (!upload.ok) { const uploadData = await upload.json(); setError(`申请已提交，附件上传失败：${uploadData.error ?? "未知错误"}`); startTransition(() => router.refresh()); return; } }
    setRequestOpen(false); setSelected([]); startTransition(() => router.refresh()); }
  return <>
    <section className="workspace-filters"><label>项目<select className="input" value={projectId} onChange={(event) => setProjectId(event.target.value)}><option value="all">全部项目</option>{Array.from(new Map(rows.map((row) => [row.projectId, String(row.projectName)])).entries()).map(([id, name]) => <option value={id} key={id}>{name}</option>)}</select></label><label>品类<select className="input" value={category} onChange={(event) => setCategory(event.target.value)}><option value="all">全部品类</option>{values("category").map((value) => <option value={value} key={value}>{value}</option>)}</select></label><label>房间<select className="input" value={room} onChange={(event) => setRoom(event.target.value)}><option value="all">全部房间</option>{values("room").map((value) => <option value={value} key={value}>{value}</option>)}</select></label><label>采购状态<select className="input" value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">全部状态</option>{values("status").map((value) => <option value={value} key={value}>{value}</option>)}</select></label><label>供应商<select className="input" value={supplier} onChange={(event) => setSupplier(event.target.value)}><option value="all">全部供应商</option>{Array.from(new Map(rows.filter((row) => row.supplierId).map((row) => [String(row.supplierId), String(row.supplierName)])).entries()).map(([id, name]) => <option value={id} key={id}>{name}</option>)}</select></label></section>
    <section className="panel procurement-table-panel"><div className="toolbar"><div><strong className="workspace-count">{filtered.length} 个 SKU</strong><span className="panel-subtitle">已选择 {selected.length} 个</span></div>{canWrite ? <button className="button primary" disabled={!selected.length} onClick={() => { setError(""); setRequestOpen(true); }}><ShoppingCart />发起采购申请</button> : null}</div><div className="table-scroll"><table className="data-table procurement-table"><thead><tr><th className="check-cell"></th><th>图片</th><th>SKU / 产品</th><th>项目</th><th>房间</th><th>品类</th><th className="right">数量</th><th className="right">预算单价</th><th className="right">最低报价</th><th>已选供应商</th><th className="right">最终采购价</th><th className="right">超预算</th><th>交期</th><th>状态</th><th></th></tr></thead><tbody>{filtered.map((row) => { const over = (Number(row.finalUnitCents ?? 0) - Number(row.budgetUnitCents ?? 0)) * Number(row.quantity); const selectable = row.status === "已核价"; return <tr key={row.id}><td className="check-cell"><input type="checkbox" disabled={!canWrite || !selectable} checked={selected.includes(row.id)} onChange={() => toggle(row.id)} aria-label={`选择 ${row.code}`} /></td><td>{row.imageUrl ? <img className="sku-thumb" src={String(row.imageUrl)} alt="" /> : <span className="sku-thumb empty-thumb"><ImageOff /></span>}</td><td><strong className="table-primary">{String(row.code)}</strong><div className="table-secondary">{String(row.name)}</div></td><td><Link className="business-link" href={`/projects/${row.projectId}`}>{String(row.projectName)}</Link></td><td>{String(row.room ?? "-")}</td><td>{String(row.category)}</td><td className="right">{Number(row.quantity).toLocaleString("zh-CN", { maximumFractionDigits: 4 })} {String(row.unit)}</td><td className="right">{formatMoney(Number(row.budgetUnitCents))}</td><td className="right">{Number(row.lowestQuoteCents) ? formatMoney(Number(row.lowestQuoteCents)) : "-"}</td><td>{row.supplierId ? <Link className="business-link" href={`/suppliers/${row.supplierId}`}>{String(row.supplierName)}</Link> : "-"}</td><td className="right">{row.finalUnitCents ? formatMoney(Number(row.finalUnitCents)) : "-"}</td><td className={`right ${over > 0 ? "danger-text" : "success-text"}`}>{row.finalUnitCents ? formatMoney(over) : "-"}</td><td>{row.leadDays ? `${row.leadDays} 天` : "-"}</td><td><span className={`badge ${getStatusTone(row.status)}`}>{row.status}</span></td><td><button className="icon-plain" onClick={() => { setDetail(row); setError(""); }} aria-label="查看 SKU 详情"><ChevronRight /></button></td></tr>; })}</tbody></table></div></section>
    {detail ? <div className="drawer-backdrop" onMouseDown={(event) => event.target === event.currentTarget && setDetail(null)}><aside className="workspace-drawer" aria-label="SKU 采购详情"><div className="modal-header"><div><div className="modal-title">{String(detail.code)} · {String(detail.name)}</div><div className="panel-subtitle">{String(detail.projectName)} / {String(detail.room)}</div></div><button className="icon-plain" onClick={() => setDetail(null)} aria-label="关闭"><X /></button></div><div className="drawer-body"><section className="drawer-product">{detail.imageUrl ? <img src={String(detail.imageUrl)} alt={String(detail.name)} /> : <div className="drawer-image-empty"><ImageOff /></div>}<div className="approval-facts"><div className="approval-fact"><span>规格</span><strong>{String(detail.specification ?? "-")}</strong></div><div className="approval-fact"><span>材质</span><strong>{String(detail.material ?? "-")}</strong></div><div className="approval-fact"><span>颜色</span><strong>{String(detail.color ?? "-")}</strong></div><div className="approval-fact"><span>数量</span><strong>{Number(detail.quantity)} {String(detail.unit)}</strong></div><div className="approval-fact"><span>预算采购价</span><strong>{formatMoney(Number(detail.budgetUnitCents))}</strong></div><div className="approval-fact"><span>预算总额</span><strong>{formatMoney(Number(detail.budgetUnitCents) * Number(detail.quantity))}</strong></div></div></section><section><h3>供应商报价</h3><div className="quote-list">{detailQuotes.map((quote) => <div className={`quote-item ${quote.status === "已选中" ? "selected" : ""}`} key={quote.id}><div className="quote-head"><Link href={`/suppliers/${quote.supplierId}`}>{String(quote.supplierName)}</Link><strong>{formatMoney(Number(quote.unitPriceCents))}</strong></div><div className="quote-grid"><span>运费 {formatMoney(Number(quote.freightCents))}</span><span>安装 {formatMoney(Number(quote.installCents))}</span><span>税率 {Number(quote.taxRateBps) / 100}%</span><span>交期 {String(quote.leadDays)} 天</span><span>{String(quote.paymentTerms ?? "-")}</span>{quote.attachmentUrl ? <a href={String(quote.attachmentUrl)} target="_blank" rel="noreferrer">查看报价单</a> : <span>无附件</span>}</div>{canWrite && quote.status !== "已选中" ? <button className="button small" disabled={pending} onClick={() => void chooseQuote(quote.id)}><Check />选择供应商</button> : null}</div>)}</div></section>{error ? <div className="form-error">{error}</div> : null}</div></aside></div> : null}
    {requestOpen ? <div className="modal-backdrop"><form className="modal" onSubmit={submitRequest}><div className="modal-header"><div><div className="modal-title">发起采购申请</div><div className="panel-subtitle">{selected.length} 个 SKU</div></div><button type="button" className="icon-plain" onClick={() => setRequestOpen(false)} aria-label="关闭"><X /></button></div><div className="form-grid"><div className="field"><label htmlFor="paymentType">付款方式</label><select className="input" id="paymentType" name="paymentType" required><option value="对公">对公</option><option value="批量私账">批量私账</option></select></div><div className="field"><label htmlFor="attachment">采购附件</label><input className="input file-input" id="attachment" name="attachment" type="file" accept=".pdf,.jpg,.jpeg,.png,.webp,.xlsx,.docx" /></div><div className="field full"><label htmlFor="reason">采购说明</label><textarea className="input" id="reason" name="reason" required /></div>{error ? <div className="form-error">{error}</div> : null}</div><div className="modal-footer"><button type="button" className="button" onClick={() => setRequestOpen(false)}>取消</button><button className="button primary" disabled={pending}>{pending ? <LoaderCircle className="animate-spin" /> : <ShoppingCart />}提交审批</button></div></form></div> : null}
  </>;
}
